<a href="https://colab.research.google.com/github/shakirhussain128/CNN-PROJECT-CODE/blob/main/object%20detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="Zxxs1pq7tlldMtYREJse")
project = rf.workspace("gbroadsdataaug").project("gb-roads-dataset-v3")
version = project.version(1)
dataset = version.download("yolov8")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.9/80.9 kB 4.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.8/66.8 kB 2.8 MB/s eta 0:00:00
  Attempting uninstall: idna
    Found existing installation: idna 3.10
    Uninstalling idna-3.10:
      Successfully uninstalled idna-3.10
loading Roboflow workspace...
loading Roboflow project...



Extracting Dataset Version Zip to gb-roads-dataset-v3-1 in yolov8:: 100%|██████████| 1334/1334 [00:01<00:00, 1033.78it/s]


In [2]:
!pip install labelImg


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 kB 6.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.2/8.2 MB 74.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.8/59.8 MB 8.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 270.5/270.5 kB 12.2 MB/s eta 0:00:00
  Created wheel for labelImg: filename=labelImg-1.8.6-py2.py3-none-any.whl size=261520 sha256=3a1dc987e333cbcce955c24856c5ea14b8a2a2ce182a6600306584a221001929
  Stored in directory: /root/.cache/pip/wheels/d9/f0/1e/74c509495458cad13a0fda23fe605e643177625cf2b5c17b34
Successfully built labelImg


In [4]:
train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(224, 224),
    batch_size=32,
    class_mode='categorical'
)

validation_generator = validation_datagen.flow_from_directory(
    validation_dir,
    target_size=(224, 224),
    batch_size=32,
    class_mode='categorical'
)


Found 579 images belonging to 2 classes.
Found 55 images belonging to 2 classes.


In [5]:
model = tf.keras.models.Sequential([
    base_model,
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(4, activation='softmax')  # 4 classes
])


In [6]:
print("Class indices:", train_generator.class_indices)


Class indices: {'images': 0, 'labels': 1}


In [8]:
model = tf.keras.models.Sequential([
    base_model,
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(4, activation='softmax')  # Set to 4 if you have 4 classes
])


In [12]:
train_dir = '/content/gb-roads-dataset-v3-1/train'
validation_dir = '/content/gb-roads-dataset-v3-1/valid'


In [13]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [14]:
train_dir = '/content/gb-roads-dataset-v3-1/train'
validation_dir = '/content/gb-roads-dataset-v3-1/valid'

train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(224, 224),
    batch_size=32,
    class_mode='categorical'
)

validation_generator = validation_datagen.flow_from_directory(
    validation_dir,
    target_size=(224, 224),
    batch_size=32,
    class_mode='categorical'
)


Found 579 images belonging to 2 classes.
Found 55 images belonging to 2 classes.


In [15]:
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.layers import Dense, Flatten, Dropout
from tensorflow.keras.models import Sequential
from sklearn.metrics import classification_report


In [16]:
train_dir = '/content/gb-roads-dataset-v3-1/train'
validation_dir = '/content/gb-roads-dataset-v3-1/valid'

image_size = (224, 224)
batch_size = 32

train_datagen = ImageDataGenerator(
    rescale=1.0/255,
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True
)

validation_datagen = ImageDataGenerator(rescale=1.0/255)

train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=image_size,
    batch_size=batch_size,
    class_mode='categorical'
)

validation_generator = validation_datagen.flow_from_directory(
    validation_dir,
    target_size=image_size,
    batch_size=batch_size,
    class_mode='categorical'
)


Found 579 images belonging to 2 classes.
Found 55 images belonging to 2 classes.


In [19]:
model = Sequential([
    tf.keras.applications.MobileNetV2(input_shape=(224, 224, 3), include_top=False, weights='imagenet'),
    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(2, activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])


In [33]:
history = model.fit(
    train_generator,
    validation_data=validation_generator,
    epochs=2,
    steps_per_epoch=train_generator.samples // batch_size,
    validation_steps=validation_generator.samples // batch_size
)


Epoch 1/2
18/18 ━━━━━━━━━━━━━━━━━━━━ 10s 301ms/step - accuracy: 1.0000 - loss: 0.0000e+00 - val_accuracy: 1.0000 - val_loss: 0.0000e+00
Epoch 2/2
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0000e+00 - val_accuracy: 1.0000 - val_loss: 0.0000e+00


In [34]:
print(next(train_generator))  # Check if data is being generated
print(next(validation_generator))  # Check validation data


(array([[[[0.38279065, 0.39205232, 0.3719461 ],
         [0.38847113, 0.39631426, 0.38718945],
         [0.43051496, 0.4383581 , 0.42779228],
         ...,
         [0.1750716 , 0.23765619, 0.20456362],
         [0.16982025, 0.23498094, 0.19576524],
         [0.17413072, 0.23687583, 0.1942658 ]],

        [[0.4169503 , 0.43362254, 0.40980008],
         [0.36294898, 0.37624106, 0.35779434],
         [0.3357938 , 0.34716478, 0.32631212],
         ...,
         [0.16992316, 0.23397873, 0.19867969],
         [0.1742332 , 0.23865838, 0.19944268],
         [0.16751131, 0.23025641, 0.18543991]],

        [[0.43372336, 0.45527235, 0.42025265],
         [0.3609625 , 0.38160136, 0.34938136],
         [0.3566607 , 0.37933746, 0.34228134],
         ...,
         [0.16477472, 0.23030128, 0.19279577],
         [0.17864615, 0.24233584, 0.20312016],
         [0.16089189, 0.223637  , 0.17661403]],

        ...,

        [[0.64869255, 0.6822535 , 0.5350686 ],
         [0.64396936, 0.68440455, 0.5190922 

In [35]:
history = model.fit(
    train_generator,
    validation_data=validation_generator,
    epochs=2,
    steps_per_epoch=train_generator.samples // batch_size,
    validation_steps=validation_generator.samples // batch_size
)


Epoch 1/2
18/18 ━━━━━━━━━━━━━━━━━━━━ 8s 321ms/step - accuracy: 1.0000 - loss: 0.0000e+00 - val_accuracy: 1.0000 - val_loss: 0.0000e+00
Epoch 2/2
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0000e+00 - val_accuracy: 1.0000 - val_loss: 0.0000e+00


In [23]:
print(next(validation_generator))


(array([[[[0.4431373 , 0.53333336, 0.32156864],
         [0.07450981, 0.1254902 , 0.01568628],
         [0.13725491, 0.15294118, 0.09411766],
         ...,
         [0.909804  , 0.90196085, 0.9450981 ],
         [0.8980393 , 0.89019614, 0.9333334 ],
         [0.8980393 , 0.8941177 , 0.92549026]],

        [[0.00392157, 0.0509804 , 0.        ],
         [0.03921569, 0.04705883, 0.02745098],
         [0.20784315, 0.20784315, 0.16862746],
         ...,
         [0.9058824 , 0.9058824 , 0.95294124],
         [0.8941177 , 0.8941177 , 0.94117653],
         [0.8941177 , 0.8941177 , 0.94117653]],

        [[0.09411766, 0.10980393, 0.05490196],
         [0.14117648, 0.13725491, 0.12156864],
         [0.13725491, 0.12156864, 0.07843138],
         ...,
         [0.8980393 , 0.9058824 , 0.9568628 ],
         [0.882353  , 0.8980393 , 0.9450981 ],
         [0.882353  , 0.8941177 , 0.95294124]],

        ...,

        [[0.45098042, 0.39607847, 0.38431376],
         [0.7019608 , 0.60784316, 0.60784316

In [24]:
steps_per_epoch = train_generator.samples // batch_size
validation_steps = validation_generator.samples // batch_size


In [25]:
steps_per_epoch = train_generator.samples // batch_size
validation_steps = validation_generator.samples // batch_size


In [36]:
history = model.fit(
    train_generator,
    validation_data=validation_generator,
    epochs=2,
    steps_per_epoch=train_generator.samples // batch_size,
    validation_steps=validation_generator.samples // batch_size
)


Epoch 1/2
18/18 ━━━━━━━━━━━━━━━━━━━━ 10s 417ms/step - accuracy: 1.0000 - loss: 0.0000e+00 - val_accuracy: 1.0000 - val_loss: 0.0000e+00
Epoch 2/2
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0000e+00 - val_accuracy: 1.0000 - val_loss: 0.0000e+00


In [37]:
for data in train_generator:
    print(data)
    break
for data in validation_generator:
    print(data)
    break


(array([[[[7.09649026e-01, 9.13570642e-01, 9.99845147e-01],
         [7.01736927e-01, 9.05658484e-01, 9.91932988e-01],
         [6.97298408e-01, 9.01219964e-01, 9.87494469e-01],
         ...,
         [9.80392247e-02, 9.80392247e-02, 9.80392247e-02],
         [9.80392247e-02, 9.80392247e-02, 9.80392247e-02],
         [9.80392247e-02, 9.80392247e-02, 9.80392247e-02]],

        [[7.08767653e-01, 9.12689269e-01, 9.98963773e-01],
         [7.01296210e-01, 9.05217767e-01, 9.91492271e-01],
         [6.96417034e-01, 9.00338590e-01, 9.86613154e-01],
         ...,
         [9.80392247e-02, 9.80392247e-02, 9.80392247e-02],
         [9.80392247e-02, 9.80392247e-02, 9.80392247e-02],
         [9.80392247e-02, 9.80392247e-02, 9.80392247e-02]],

        [[7.07886338e-01, 9.11807895e-01, 9.98082399e-01],
         [7.00855553e-01, 9.04777110e-01, 9.91051674e-01],
         [6.95535660e-01, 8.99457276e-01, 9.85731781e-01],
         ...,
         [9.80392247e-02, 9.80392247e-02, 9.80392247e-02],
         

In [39]:
print(train_generator.class_indices)



{'images': 0, 'labels': 1}


In [40]:
# For two classes, for example, 0 and 1
labels = [0, 1]
print(classification_report(y_true, y_pred_classes, labels=labels, target_names=["Class 0", "Class 1"]))


              precision    recall  f1-score   support

     Class 0       1.00      1.00      1.00        55
     Class 1       0.00      0.00      0.00         0

    accuracy                           1.00        55
   macro avg       0.50      0.50      0.50        55
weighted avg       1.00      1.00      1.00        55



Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
Recall is ill-defined and bei

In [41]:
y_true = validation_generator.classes
print(y_true[:10])  # Print first 10 true labels
print(y_pred_classes[:10])  # Print first 10 predicted labels


[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]


In [42]:
# Ensure y_true and y_pred_classes are aligned in terms of class labels
y_true = validation_generator.classes
y_pred = model.predict(validation_generator)
y_pred_classes = y_pred.argmax(axis=-1)

# Check the class indices
print(train_generator.class_indices)

# Ensure correct labels (e.g., 0 and 1 for two classes)
labels = [0, 1]  # or match according to your dataset
print(classification_report(y_true, y_pred_classes, labels=labels, target_names=["Class 0", "Class 1"]))


2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step
{'images': 0, 'labels': 1}
              precision    recall  f1-score   support

     Class 0       1.00      1.00      1.00        55
     Class 1       0.00      0.00      0.00         0

    accuracy                           1.00        55
   macro avg       0.50      0.50      0.50        55
weighted avg       1.00      1.00      1.00        55



Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
Recall is ill-defined and bei

In [43]:
!git clone https://github.com/ultralytics/yolov5.git
%cd yolov5
!pip install -r requirements.txt


Cloning into 'yolov5'...
remote: Enumerating objects: 17045, done.
remote: Counting objects: 100% (23/23), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 17045 (delta 10), reused 18 (delta 8), pack-reused 17022 (from 1)
Receiving objects: 100% (17045/17045), 15.66 MiB | 15.79 MiB/s, done.
Resolving deltas: 100% (11700/11700), done.
/content/yolov5/yolov5


In [31]:
!python train.py --img 640 --batch 16 --epochs 50 --data /path/to/data.yaml --weights yolov5s.pt


Creating new Ultralytics Settings v0.0.6 file ✅ 
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.
wandb: WARNING ⚠️ wandb is deprecated and will be removed in a future release. See supported integrations at https://github.com/ultralytics/yolov5#integrations.
2024-11-10 16:54:12.046697: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-11-10 16:54:12.066101: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-11-10 16:54:12.072052: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to regi

In [49]:
train_path = "../content/gb-roads-dataset-v3-1/train"



In [61]:
train = "/content/gb-roads-dataset-v3-1/train"
valid = "/content/gb-roads-dataset-v3-1/valid"


In [63]:
!python val.py --weights runs/train/exp/weights/best.pt --data /path/to/data.yaml --img 640


Traceback (most recent call last):
  File "/content/yolov5/yolov5/val.py", line 603, in <module>
    opt = parse_opt()
  File "/content/yolov5/yolov5/val.py", line 541, in parse_opt
    opt.data = check_yaml(opt.data)  # check YAML
  File "/content/yolov5/yolov5/utils/general.py", line 479, in check_yaml
    return check_file(file, suffix)
  File "/content/yolov5/yolov5/utils/general.py", line 507, in check_file
    assert len(files), f"File not found: {file}"  # assert file was found
AssertionError: File not found: /path/to/data.yaml
